language: python

cache:
  - pip

python:
  - "3.5"

before_install:
  - pip install --ugrade pip

install:
  - pip install -r requirements.txt

script:
  - flake8
  - isort -c
  - coverage run --source . src/manage.py test
  - coverage report --fail-under=100
